### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by pixie79** [prajwalrao/ambari-metrics-grafana#1]
Hi,

I have been looking over this module - but where do you specify the cluster in use as ambari can serve many clusters and the previous version which does not work for the latest grafana had a cluster name option.

Regards

Mark

**Comment by prajwalrao** [comment]
@pixie79 This module does not need the cluster name as we use the [AMS API Endpoint](https://cwiki.apache.org/confluence/display/AMBARI/Metrics+Collector+API+Specification) and not the [Ambari API](https://cwiki.apache.org/confluence/display/AMBARI/Ambari+Metrics+API+specification) that was used with the earlier version. AMS API provides a **metadata** endpoint that can be accessed via `collectorhost:6188/ws/v1/timeline/metrics/metadata` and this plugin is built to take full advantage of that endpoint.

**Comment by prajwalrao** [comment]
Closing this. Let me know if you need any further clarification.
