### ISSUE TITLE
Can't get beyond login on HDP 3

### ISSUE THREAD

**Issue by aijanai** [prajwalrao/ambari-metrics-grafana#10]
Hi,

I am using Grafana 6.0.2 to get data out of Ambari Metrics on Hortonworks HDP 3.0.1.

The plugin installs fine and the new datasource type appears, but I am having difficulties in getting past the login screen in Ambari Metrics' Grafana.

It works if I login on AMS and use "Browser" Access type: in this case my browser will correctly pass the cookie along the request and the datasource link will be successfully established.

So it totally looks like it's a login problem at Ambari's Grafana screen. Basic Auth form doesn't really seem to pass the credentials.

Does this need to be reimplemented for Grafana 6.x or HDP 3.x?

**Comment by prajwalrao** [comment]
@aijanai I haven't tried this with Grafana 6.x or with HDP 3.x. Let me give it a shot and I'll get back to you on this.

**Comment by aijanai** [comment]
It works, indeed. It was my fault, plugging the port of Ambari, instead of Ambari Metrics...

**Comment by prajwalrao** [comment]
Thank you for clarifying that @aijanai . I appreciate it.
