### ISSUE TITLE
Getting not found while creating dashboard

### ISSUE THREAD

**Issue by ajayanaj** [prajwalrao/ambari-metrics-grafana#12]
Hi,

I have installed Ambari metrics datasource plugin and configured without any issues, but the issue am facing is I'm getting "not found" error while trying to create dashboard. 

![image](https://user-images.githubusercontent.com/45065725/58635247-039cd700-830b-11e9-89be-ae6a9ed3c9a0.png)

Grafana version: 6.0
PS: We installed Ambari plugin through ansible.

Can anyone help us here?

**Comment by prajwalrao** [comment]
@ajayanaj Is your datasource working right? I've never used Ansible to install Ambari, but I doubt that would be a concern. 

- Can you check your datasource and make sure your AMS (Ambari Metrics Server) host is configured correctly. 

- Can you access your AMS host directly? (usually http://amshost:6188)

**Comment by ajayanaj** [comment]
@prajwalrao Thanks for the reply. Yes, it's configured correctly and I doubt the issue at the AMS host level, I will check that and update here if I need any further help.

Thanks again.

**Comment by ajayanaj** [comment]
@prajwalrao I checked the AMS host and it's configured properly. Also, I'm able to access AMS host directly. 
While debugging the issue I noticed the error as Failed to load resource: the server responded with a status of 404 (), So I tried to make a curl request and got 404 response as well.
curl -XGET  http://ambarihost.com:8080/ws/v1/timeline/metrics/metadata
{
  "status": 404,
  "message": "Not Found"
}

But we are able to access below API.
curl -GET  http://ambarihost.com:8080/api/v1/clusters/hadoop_delta4/services/AMBARI_METRICS/components/METRICS_COLLECTOR

I just wanted to know if the plugin is trying to make connections to wrong API or do we need to allow access to the above API from AMS host? (I don't see any options in AMS host to allow connections for this API: /ws/v1/timeline/metrics/metadata)

**Comment by prajwalrao** [comment]
@ajayanaj I think that solves the mystery. The path is different when ambari is installed via ansible (i assume). The plugin looks for ````ws/v1/```` whereas the path to your install is at ````api/v1````. 

**For a quick and dirty fix:**
If you can edit your datasource.js and replace the references of ````ws/v1/````  to ````api/v1/```` , you should have a functioning plugin. There should be 10 instances.

On my end, I will work on parametrizing that or adding to the plugin config and try and make sure nothing else breaks.

Hope that helps. Let me know how it goes.
