### ISSUE TITLE
Ambari metrics plugin doesn't work with templated data sources

### ISSUE THREAD

**Issue by perfectayush** [prajwalrao/ambari-metrics-grafana#4]
We are running 2 seperate ambari clusters and we have a common grafana instance.

Using grafana's template variables, I am templating the 2 ambari data sources, but the graphs fail to load when using templated data source in the dashboard. I think there is some bug in the plugin code which isn't allowing the templated data source to work.

It would be really useful to make this work in a single grafana instance and without creating multiple dashboards for each data source.

**Comment by prajwalrao** [comment]
The plugin in its current state doesn't support multiple datasources for a templatized dashboard. You can still do multiple datasources on a single dashboard, but not on a templatized dashboard.

You can set the query editor to "mixed" mode to be able to visualize specific metrics for different data sources and plot them on the same graph.

I'll look into the complexity and challenges of implementing this feature and get back to you.

**Comment by prajwalrao** [comment]
@perfectayush On further inspection, the plugin is ready for templatized data sources. Here are the steps to get it working ( I think you might have missed the last part)
-  Add Templating Variable for Datasource (let's call it **ds**)
-  Save Dashboard
-  Edit the graphs on your dashboard to make sure the "Panel Data Source" is set to "**$ds**"  and not anything else. You will need to do it for each graph and you should be able to see Graphs from 2 different datasources in the same dashboard.

Closing this for now, let me know if you have any further issues.
