### ISSUE TITLE
Support for Ambari 2.4.0

### ISSUE THREAD

**Issue by vgrivel** [prajwalrao/ambari-metrics-grafana#5]
Hi,

Ambari 2.4.0 comes with Storm Dashboard for Grafana and used specific templating. Did you plan to update your plugin to support ambari 2.4.0 ? https://github.com/apache/ambari/tree/release-2.4.0/ambari-metrics/ambari-metrics-grafana/ambari-metrics

Thank you.

**Comment by prajwalrao** [comment]
hey @vgrivel - This will be added in the next update. Expect it within this week.

**Comment by vgrivel** [comment]
Awesome, thanks!

**Comment by vgrivel** [comment]
Do you have any update on the support for ambari 2.4.0? Thanks

**Comment by prajwalrao** [comment]
@vgrivel I updated it to work with Grafana > v4.5.x and tested it with Ambari v2.7.0.
