### ISSUE TITLE
How to alert

### ISSUE THREAD

**Issue by cuihz** [prajwalrao/ambari-metrics-grafana#6]
Hi, I'm newbee to Grafana. I use this plugin on my Grafana, but I found that the ambari metric datasource does't support alert. I found that alert seems implemented through go however datasource by Javascript. So I wonder how to add alert on ambari metric datasource or any patchs or any others suggestions

**Comment by srini3463** [comment]
@prajwalrao @cuihz 

Please provide if you have any updates on supporting alerts with Ambari Metrics data source and Grafana.

Thanks.

**Comment by prajwalrao** [comment]
@cuihz @srini3463 This depends on - https://github.com/grafana/grafana/issues/6841 being implemented. This is based on this comment here - https://github.com/grafana/grafana/issues/12221#issuecomment-395992762

**Comment by cuihz** [comment]
@srini3463  I don't use the alert feature. In my company, monitor and alert are supported by a common lib developed by a team. They provide an http interface that mock as an ambari metric collector server and I config this http address in all my big data compoments config. After this, I could see the metric on our company common grafana and config alert.
