### ISSUE TITLE
Ambari plugin failed

### ISSUE THREAD

**Issue by sandats** [prajwalrao/ambari-metrics-grafana#7]
When adding a data source, a plug-in failure occurs together with the following message.

Ambari plugin failed
Plugin module is missing Datasource constructor

I looked for this solution but I could not find it.
The version of Grafana is 4.6.0

**Comment by srini3463** [comment]
I am also getting the same error. Please let me know if you have any updates.

lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/app/plugins/datasource/praj-ams-datasource/module status=404

Thanks.

**Comment by prajwalrao** [comment]
@srini3463 @sandats Was this only on v4.6.0 of Grafana? Are you still facing issues? I have tried with v5.2.4 and it works fine.
