### ISSUE TITLE
Kafka - Hosts Dashboard: JS error in panel templateSrv._index is undefined

### ISSUE THREAD

**Issue by jsbraich** [prajwalrao/ambari-metrics-grafana#8]
I'm noticing this error "templateSrv._index is undefined" on  imported 'Kafka - Hosts' dashboard (used latest from this github repo), and as soon I change datasource to my Ambari datasource. I see this message on the panel "templateSrv._index is undefined".

**Environment**
Grafana: 5.2.2-1

Stack Trace
`AmbariMetricsDatasource/this.query@http://<ip_addr>:3000/public/plugins/praj-ams-datasource/datasource.js:232:1
1534/f</e.prototype.issueQueries@http://<ip_addr>:3000/public/build/0.5c89ac3fc7a3e78b3629.js:7:17847
1597/p</e.prototype.issueQueries@http://<ip_addr>:3000/public/build/0.5c89ac3fc7a3e78b3629.js:7:214503
u@http://10.30.27.169:3000/public/build/vendor.0cea50118711e7e6c839.js:87:69119
l/<@http://10.30.27.169:3000/public/build/vendor.0cea50118711e7e6c839.js:87:69565
$digest@http://10.30.27.169:3000/public/build/vendor.0cea50118711e7e6c839.js:87:75262
$apply@http://10.30.27.169:3000/public/build/vendor.0cea50118711e7e6c839.js:87:77074
A/s<@http://10.30.27.169:3000/public/build/vendor.0cea50118711e7e6c839.js:87:73133
i@http://10.30.27.169:3000/public/build/vendor.0cea50118711e7e6c839.js:87:21976
me/l.defer/n<@http://10.30.27.169:3000/public/build/vendor.0cea50118711e7e6c839.js:87:23440`

**Comment by prajwalrao** [comment]
Fixed with https://github.com/prajwalrao/ambari-metrics-grafana/commit/d429f53128fc8db3be7f719f153d228b643189eb
